services:
  - type: web
    name: holla-urban-web
    env: static
    buildCommand: |
      wget -q https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.41.0-stable.tar.xz -O flutter.tar.xz
      tar xf flutter.tar.xz
      export PATH="$PATH:$(pwd)/flutter/bin"
      flutter config --no-analytics
      flutter pub get
      flutter build web --release --web-renderer canvaskit
    staticPublishPath: build/web
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /flutter.js
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /main.dart.js
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
